Controllers/NewTaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToDoList.Models;

namespace ToDoList.Controllers
{
    public class NewTaskController : Controller
    {
        // GET: NewTask
        DBToDoListEntities db = new DBToDoListEntities();

        public ActionResult Index()
        {
            if (Session["UserID"] == null)
            {
                Session["UserID"] = null;
                return RedirectToAction("Login", "Account");
            }
            return View();
        }
        public ActionResult AddNewTask()
        {
            if (Session["UserID"] == null)
            {
                Session["Name"] = null;
                return RedirectToAction("Login", "Account");
            }

            List<tblPriority> list = db.tblPriorities.ToList();
            ViewBag.PriorityList = new SelectList(list, "PriorityID", "Priority");

            return View();
        }
        [HttpPost]
        public ActionResult AddNewTask(Task model)
        {

            List<tblPriority> list = db.tblPriorities.ToList();
            ViewBag.PriorityList = new SelectList(list, "PriorityID", "Priority");

            if (Session["UserID"] == null)
            {
                Session["Name"] = null;
                return RedirectToAction("Login", "Account");
            }
            else
            {
                int ID = Convert.ToInt32(Session["UserID"]);

                if (model.TaskID > 0) //EDITS THE EXISTING RECORD IN tblTasks
                {
                    if (model.StartDate >= DateTime.Now.Date && model.EndDate >= model.StartDate)
                    {
                        if (model.StartTime == null || model.StartTime >= DateTime.Now.TimeOfDay)
                        {
                            if (model.EndTime == null || (model.EndTime >= model.StartTime && model.StartDate == model.EndDate) || (model.EndDate > model.StartDate))
                            {
                                tblTask objtblTaskUpdated = db.tblTasks.SingleOrDefault(x => x.TaskID == model.TaskID && x.ID == ID);

                                objtblTaskUpdated.Title = model.Title;
                                objtblTaskUpdated.TaskDetail = model.TaskDetail;
                                objtblTaskUpdated.StartDate = model.StartDate;
                                objtblTaskUpdated.StartTime = model.StartTime;
                                objtblTaskUpdated.EndDate = model.EndDate;
                                objtblTaskUpdated.EndTime = model.EndTime;
                                objtblTaskUpdated.Completed = model.Completed;
                                objtblTaskUpdated.PriorityID = model.PriorityID;

                                db.SaveChanges();
                            }
                            else
                            {
                                ViewBag.EndTime = "alert";
                            }
                        }
                        else
                        {
                            ViewBag.StartTime = "alert";
                        }
                    }
                    else
                    {
                        ViewBag.StartEndDate = "alert";
                    }
                }
                else //ADDS NEW RECORD TO tblTasks
                {
                    if (model.StartDate >= DateTime.Now.Date && model.EndDate >= model.StartDate)
                    {
                        if (model.StartTime == null || model.StartTime >= DateTime.Now.TimeOfDay)
                        {
                            if (model.EndTime == null || (model.EndTime >= model.StartTime && model.StartDate == model.EndDate) || model.StartDate<model.EndDate)
                            {
                                tblTask objtblTask = new tblTask();

                                objtblTask.Title = model.Title;
                                objtblTask.TaskDetail = model.TaskDetail;
                                objtblTask.StartDate = model.StartDate;
                                objtblTask.StartTime = model.StartTime;
                                objtblTask.EndDate = model.EndDate;
                                objtblTask.EndTime = model.EndTime;
                                objtblTask.Completed = 0;
                                objtblTask.PriorityID = model.PriorityID;
                                objtblTask.ID = Convert.ToInt32(Session["UserID"]);

                                db.tblTasks.Add(objtblTask);
                                db.SaveChanges();

                                ViewBag.Javascript = "alert";
                            }
                            else
                            {
                                ViewBag.EndTime = "alert";
                            }
                        }
                        else
                        {
                            ViewBag.StartTime = "alert";
                        }
                    }
                    else
                    {
                        ViewBag.StartEndDate = "alert";
                    }
                }
                return View(model);
            }
        }
    }
}

Views/NewTask/AddNewTask.cshtml
@model ToDoList.Models.Task
@{
    ViewBag.Title = "AddNewTask";
}

<div><a href="/MyTasks/ViewTask">View your tasks</a></div>

<h2>Add New Task</h2>
<style>
    .error {
        color: red;
    }
</style>

@using (Html.BeginForm("AddNewTask", "NewTask", FormMethod.Post))
{
    if (Session["UserID"] != null)
    {
        @*<form id="AddNewTaskForm">*@
        <div class="form-group">
            @Html.LabelFor(model => model.Title, "Title")
            @Html.TextBoxFor(model => model.Title, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "error" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.TaskDetail, "Task")
            @Html.TextAreaFor(model => model.TaskDetail, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, "Start Date")
            @Html.TextBoxFor(model => model.StartDate, new { @class = "form-control datepicker", @type = "date" })
            @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "error" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.StartTime, "Start Time")
            @Html.TextBoxFor(model => model.StartTime, new { @id = "timepicker", @class = "form-control", @type = "time" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, "End Date")
            @Html.TextBoxFor(model => model.EndDate, new { @class = "form-control datepicker", @type = "date" })
            @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "error" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.EndTime, "End Time")
            @Html.TextBoxFor(model => model.EndTime, new { @id = "timepicker", @class = "form-control", @type = "time" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Priority, "Priority")
            @Html.DropDownListFor(model => model.PriorityID, ViewBag.PriorityList as SelectList, "--Select--", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.PriorityID, "", new { @class = "error" })
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="SAVE" />
        </div>
        if (ViewBag.Javascript == "alert")
        {
            <script>alert("Task Added."); </script>
        }
        if (ViewBag.StartEndDate == "alert")
        {
            <script>alert("Failed adding Task. Enter Valid Dates."); </script>

        }
        if (ViewBag.StartTime== "alert")
        {
            <script>alert("Failed adding Task. Enter Valid Start Time."); </script>

        }
        if (ViewBag.EndTime == "alert")
        {
            <script>alert("Failed adding Task. Enter Valid End Time."); </script>

        }
    }
}

Views/NewTask/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>